### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by SimonAKing** [linkFly6/ts-router-to-controller#1]
你好，我最近在读你的 ts系列文章，写的通俗易懂！我非常感谢你的付出，已 follow  😄 
不过我发现，这么好的系列文章 阅读量才几百，实在很可惜，建议将文章转载到掘金网站，只需要 分享链接就行了！很简单的~

**Comment by linkFly6** [comment]
因为网站在今年重写了，所以历史浏览的数据都没有迁移。

TS 系列文章其实浏览量已经破万了。

非常感谢您的关注，当然也期望您能够帮助我推广下，一同为 TypeScript 的发展共尽绵力。
